<a href="https://colab.research.google.com/github/SHUBHAM6247/AI_ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
d = np.array([5,6,7])

In [ ]:
e=a+d

In [ ]:
e

array([ 6,  8, 10])

In [ ]:
f = np.array([(2.5,8,7), (7,8,9)], dtype = float)

In [ ]:
f

array([[2.5, 8. , 7. ],
       [7. , 8. , 9. ]])

In [ ]:
g=b+f

In [ ]:
g

array([[ 4., 10., 10.],
       [11., 13., 15.]])

In [ ]:
b = f = np.array([(7,3,1), (14,15,36)], dtype = float)

In [ ]:
f

array([[ 7.,  3.,  1.],
       [14., 15., 36.]])

In [ ]:
f.sort()

In [ ]:
f

array([[ 1.,  3.,  7.],
       [14., 15., 36.]])

In [ ]:
b

array([[ 1.,  3.,  7.],
       [14., 15., 36.]])